import { TokenDefinitions } from "../types";

export const scale: TokenDefinitions = {
  properties: [
    '-webkit-margin-after',
    '-webkit-margin-before',
    '-webkit-padding-after',
    '-webkit-padding-before',
    '-webkit-shape-margin',
    'border-bottom-left-radius',
    'border-bottom-right-radius',
    'border-bottom-width',
    'border-left-width',
    'border-radius',
    'border-right-width',
    'border-top-left-radius',
    'border-top-right-radius',
    'border-top-width',
    'border-width',
    'column-gap',
    'font-size',
    'gap',
    'height',
    'line-height',
    'margin-block-end',
    'margin-block-start',
    'margin-block',
    'margin-bottom',
    'margin-inline-end',
    'margin-inline-start',
    'margin-inline',
    'margin-left',
    'margin-right',
    'margin-top',
    'margin',
    'max-height',
    'max-width',
    'min-height',
    'min-width',
    'padding-block-end',
    'padding-block-start',
    'padding-block',
    'padding-bottom',
    'padding-inline-end',
    'padding-inline-start',
    'padding-inline',
    'padding-left',
    'padding-right',
    'padding-top',
    'padding',
    'row-gap',
    'scroll-margin-bottom',
    'scroll-margin-left',
    'scroll-margin-right',
    'scroll-margin-top',
    'scroll-margin',
    'scroll-padding-block-end',
    'scroll-padding-block-start',
    'scroll-padding-block',
    'scroll-padding-bottom',
    'scroll-padding-inline-end',
    'scroll-padding-inline-start',
    'scroll-padding-inline',
    'scroll-padding-left',
    'scroll-padding-right',
    'scroll-padding-top',
    'scroll-padding',
    'scroll-snap-inline-block',
    'scroll-snap-margin-block-end',
    'scroll-snap-margin-block-start',
    'scroll-snap-margin-block',
    'scroll-snap-margin-bottom',
    'scroll-snap-margin-inline-end',
    'scroll-snap-margin-inline-start',
    'scroll-snap-margin-left',
    'scroll-snap-margin-right',
    'scroll-snap-margin-top',
    'shape-margin',
    'width',
    'top',
    'right',
    'bottom',
    'left',
  ],    
  tokens: {
    '0': '0',
    '1': '0.0625rem',
    '2': '0.125rem',
    '3': '0.25rem',
    '4': '0.375rem',
    '5': '0.5rem',
    '6': '0.625rem',
    '7': '0.75rem',
    '8': '0.875rem',
    '9': '0.9375rem',
    '10': '1rem',
    '15': '1.5rem',
    '20': '2rem',
    '25': '2.5rem',
    '30': '3rem',
    '35': '3.5rem',
    '40': '4rem',
    '45': '4.5rem',
    '50': '5rem',
    '55': '5.5rem',
    '60': '6rem',
    '65': '6.5rem',
    '70': '7rem',
    '75': '7.5rem',
    '80': '8rem',
    '85': '8.5rem',
    '90': '9rem',
    '95': '9.5rem',
    '100': '10rem',
    '150': '15rem',
    '200': '20rem',
    '250': '25rem',
    '300': '30rem',
    '350': '35rem',
    '400': '40rem',
    '450': '45rem',
    '500': '50rem',
    '550': '55rem',
    '600': '60rem',
    '650': '65rem',
    '700': '70rem',
    '750': '75rem',
    '800': '80rem',
    '850': '85rem',
    '900': '90rem',
  },  
}